--- #YAML:1.0
name:               Data-ES-Senado
version:            0.0.7
abstract:           Clase base para representar los datos del Senado español
author:
    - JJ Merelo <jj@merelo.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBIx::Class:  0
    File::Slurp:  0
    LWP::Simple:  0
    Test::More:   0
    version:      0
    YAML:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
